-- MySQL Script generated by MySQL Workbench
-- Fri Feb 12 16:18:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbeventdash
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbeventdash
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbeventdash` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dbeventdash` ;

-- -----------------------------------------------------
-- Table `dbeventdash`.`itmn_alarme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbeventdash`.`itmn_alarme` (
  `id_alarme` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_alarme`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbeventdash`.`itmn_equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbeventdash`.`itmn_equipamento` (
  `id_equip` INT NOT NULL AUTO_INCREMENT,
  `hostname` VARCHAR(50) NOT NULL,
  `ipaddr` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_equip`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbeventdash`.`itmn_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbeventdash`.`itmn_evento` (
  `num_seq` INT NOT NULL AUTO_INCREMENT,
  `data_evt` DATE NULL DEFAULT NULL,
  `id_alarme` INT NOT NULL,
  `id_equip` INT NOT NULL,
  PRIMARY KEY (`num_seq`),
  INDEX `fk_alarme` (`id_alarme` ASC) VISIBLE,
  INDEX `fk_equip` (`id_equip` ASC) VISIBLE,
  CONSTRAINT `fk_alarme`
    FOREIGN KEY (`id_alarme`)
    REFERENCES `dbeventdash`.`itmn_alarme` (`id_alarme`),
  CONSTRAINT `fk_equip`
    FOREIGN KEY (`id_equip`)
    REFERENCES `dbeventdash`.`itmn_equipamento` (`id_equip`))
ENGINE = InnoDB
AUTO_INCREMENT = 1501
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbeventdash`.`itmn_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbeventdash`.`itmn_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `email_usuario` VARCHAR(100) NOT NULL,
  `racf_usuario` VARCHAR(7) NOT NULL,
  `senha_usuario` VARCHAR(50) NOT NULL,
  `ramal_usuario` VARCHAR(10) NULL DEFAULT NULL,
  `link_foto` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_usuario_UNIQUE` (`email_usuario` ASC) VISIBLE,
  UNIQUE INDEX `racf_usuario_UNIQUE` (`racf_usuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
